title: 'Crowd Up'
default_lang: en
author:
  name: 'Austin Rivas'
  email: austinrivas@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Crowd Up Meta Description'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
